# Generated by Django 3.2.20 on 2023-10-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('adjective_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjective_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_adjectives', models.ManyToManyField(to='app_ventana.Adjective')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventana.token')),
            ],
        ),
        migrations.CreateModel(
            name='AntonymPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective1_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonym_pairs_1', to='app_ventana.adjective')),
                ('adjective2_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonym_pairs_2', to='app_ventana.adjective')),
            ],
        ),
        migrations.AddField(
            model_name='adjective',
            name='antonyms',
            field=models.ManyToManyField(related_name='_app_ventana_adjective_antonyms_+', through='app_ventana.AntonymPair', to='app_ventana.Adjective'),
        ),
    ]
